import {
  Film, Music, Trophy, Theater, Laugh, Presentation, Wrench, Tent, Laptop, Ticket, QrCode, ScanLine, Store, Users, HandHeart, ShieldCheck, Wallet, Gift, Award, Heart, Share2, MapPin, Star, Search, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Clock, Calendar, X, Menu, User, LogOut, Download, Mail, MessageSquare, RotateCcw, Send, Bell, BarChart3, Settings, FileText, Building2, Percent, Megaphone, LifeBuoy, History, CheckCircle2, XCircle, AlertTriangle, Plus, Trash2, Pencil, Eye, EyeOff, Printer, Banknote, CreditCard, Smartphone, Landmark, Flame, Sparkles, Crown, Medal, Filter, ArrowLeft, ArrowRight, Minus, LayoutDashboard, Armchair, Camera, Timer, Copy, Globe, Home, Circle, Info, ThumbsUp, Languages, Tag, Lock, RefreshCw, ArrowRightLeft, Ban, Activity, DoorOpen, UserCheck, ClipboardList, Hourglass, CalendarPlus, Grid3x3, Layers, Receipt, TrendingUp, ExternalLink, LogIn, Check, PartyPopper, Zap, Map, Upload, BadgeCheck, Plug, Save, Rocket, LayoutGrid, SlidersHorizontal, Pause, Play, Code, ZoomIn, ZoomOut, KeyRound, FileCheck2, Building, Link2, Maximize2, Palette, ListChecks, CircleDollarSign, Undo2, Redo2, MousePointer2, Square, Pentagon, MousePointerClick, PenTool, GripVertical, ArrowUp, ArrowDown, Image, Type, Brush, UserPlus, Shield,
} from 'lucide-react';

const MAP = { Film, Music, Trophy, Theater, Laugh, Presentation, Wrench, Tent, Laptop, Ticket, QrCode, ScanLine, Store, Users, HandHeart, ShieldCheck, Wallet, Gift, Award, Heart, Share2, MapPin, Star, Search, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Clock, Calendar, X, Menu, User, LogOut, Download, Mail, MessageSquare, RotateCcw, Send, Bell, BarChart3, Settings, FileText, Building2, Percent, Megaphone, LifeBuoy, History, CheckCircle2, XCircle, AlertTriangle, Plus, Trash2, Pencil, Eye, EyeOff, Printer, Banknote, CreditCard, Smartphone, Landmark, Flame, Sparkles, Crown, Medal, Filter, ArrowLeft, ArrowRight, Minus, LayoutDashboard, Armchair, Camera, Timer, Copy, Globe, Home, Circle, Info, ThumbsUp, Languages, Tag, Lock, RefreshCw, ArrowRightLeft, Ban, Activity, DoorOpen, UserCheck, ClipboardList, Hourglass, CalendarPlus, Grid3x3, Layers, Receipt, TrendingUp, ExternalLink, LogIn, Check, PartyPopper, Zap, Map, Upload, BadgeCheck, Plug, Save, Rocket, LayoutGrid, SlidersHorizontal, Pause, Play, Code, ZoomIn, ZoomOut, KeyRound, FileCheck2, Building, Link2, Maximize2, Palette, ListChecks, CircleDollarSign, Undo2, Redo2, MousePointer2, Square, Pentagon, MousePointerClick, PenTool, GripVertical, ArrowUp, ArrowDown, Image, Type, Brush, UserPlus, Shield };

export default function Icon({ name, ...p }) {
  const C = MAP[name] || Circle;
  return <C {...p} />;
}
